# Monte Carlo Simulation 

Problem Statement: Evaluating mean and standard deviation of the profits from fixed-strike Arithmetic option.
The value of option at expiry is defined by $V=max[\sum_{t=1}^T S_t - X,0]$ , here $S_t$ is the closing price of the underlying asset at time t and T is the number of periods in the life of the option. 

We assume that there are 200 days until expiry. And the returns have lognormal distribution with the mean $\mu$ = 10% and the standard deviation $\sigma$ = 20%

In [1]:
import numpy as np

In [13]:
num_days = 200
num_trials = 10000
ret_arr = np.zeros((num_trials,num_days))
strike_price = 100 #assumed
option_value_arr = np.zeros(num_trials)

In [16]:
for i in range(num_trials):
    ret_arr[i,:] = np.random.normal(10,20,200)
    option_value = np.mean(ret_arr[i,:]) - strike_price
    #if option_value > 0:
    option_value_arr[i] = option_value
    #else:
    #option_value_arr[i] = 0

In [17]:
option_value_arr

array([-90.58284182, -88.46953333, -90.47963846, ..., -87.61636865,
       -89.7645215 , -89.38978897])

In [18]:
ret_arr

array([[ 29.84710739, -21.90226514,  16.33340389, ...,   3.82662042,
         18.59560994, -42.87991144],
       [-41.47864855,  29.75688432,  31.55221181, ...,   1.87409642,
         32.87500515,   3.30944667],
       [ 22.69892229,  -0.23815413,  76.90679828, ...,  28.38850482,
          8.02642097,  -9.93148958],
       ...,
       [ 24.27048449, -25.2003621 ,  -9.03404317, ...,  33.33952977,
          0.71341973,  15.95572607],
       [-19.17355775,  28.35941916,  55.68037655, ...,  -8.43770669,
         42.14380202, -15.65210876],
       [  1.90944075,  21.96718802,  38.17950096, ...,  10.26704469,
         28.44310805,  -4.11057997]])

In [22]:
sample = np.zeros((4,4))

In [26]:
sample[3,:] = np.array([1,2,3,4])

In [27]:
sample

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 2., 3., 4.]])

In [28]:
np.mean(sample[3,:])

2.5